# Generated by Django 4.0.6 on 2022-07-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imageUrl',
            field=models.CharField(max_length=1000),
        ),
    ]
